version: '3.9'

services:

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
    deploy:
      resources:
          limits:
            cpus: '1.0'
            memory: 128M

  app:
    build: .
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 128M